services:
  - type: web
    name: Unique Ijay's Limited
    env: node
    buildCommand: npm run build
    startCommand: npm run start:prod
    staticPublishPath: build/
    routes:
      - type: rewrite
        source: /(.*)$
        destination: /index.html
